apiVersion: example.my.domain/v1alpha1
kind: MyApp
metadata:
  labels:
    app.kubernetes.io/name: gooperator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-sample
spec:
  # TODO(user): Add fields here
